#!/usr/bin/env python3
"""Validate appearance facts and both deterministic Markdown reports."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from build_appearance_reports import build_appearance_data

APPEARANCE_ID_RE = re.compile(r"^APP-(P[0-9]{2,})-([0-9]{4})$")


def validate_appearance_reports(project_dir: Path) -> list[str]:
    project_dir = project_dir.resolve()
    data_path = project_dir / "data" / "appearances" / "appearances.json"
    chapter_report = project_dir / "deliverables" / "全角色章节出镜表.md"
    major_report = project_dir / "deliverables" / "主要角色场景统计.md"
    try:
        current = json.loads(data_path.read_text(encoding="utf-8"))
        current_chapter = chapter_report.read_text(encoding="utf-8")
        current_major = major_report.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return [f"appearance outputs unreadable: {exc}"]
    errors: list[str] = []
    if current.get("schema_version") != "2.0.0" or current.get("appearance_version") != "appearance-registry-v1":
        errors.append("appearance bundle version is invalid")
    appearances = current.get("appearances")
    if not isinstance(appearances, list):
        errors.append("appearances must be an array")
        appearances = []
    ids: list[str] = []
    observations: list[str] = []
    for item in appearances:
        if not isinstance(item, dict):
            errors.append("appearance record is not an object")
            continue
        appearance_id = str(item.get("appearance_id"))
        observation_id = str(item.get("source_observation_id"))
        match = APPEARANCE_ID_RE.fullmatch(appearance_id)
        if not match or observation_id != f"COBS-{match.group(1)}-{match.group(2)}":
            errors.append(f"{appearance_id}: appearance ID does not match its source observation")
        if item.get("has_dialogue") != bool(item.get("speaker_segment_ids")):
            errors.append(f"{appearance_id}: dialogue flag and speaker segments disagree")
        ids.append(appearance_id)
        observations.append(observation_id)
    if len(ids) != len(set(ids)) or len(observations) != len(set(observations)):
        errors.append("appearance IDs or source observations are duplicated")
    try:
        expected, expected_chapter, expected_major = build_appearance_data(project_dir)
    except (OSError, ValueError, KeyError, TypeError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        errors.append(f"appearance reports cannot be rebuilt: {exc}")
    else:
        if current != expected:
            errors.append("appearance data differs from deterministic rebuild")
        if current_chapter != expected_chapter:
            errors.append("character chapter Markdown differs from deterministic rebuild")
        if current_major != expected_major:
            errors.append("major character Markdown differs from deterministic rebuild")
    if list(project_dir.glob("deliverables/全角色章节出镜表.docx")) or list(project_dir.glob("deliverables/主要角色场景统计.docx")):
        errors.append("DOCX duplicates must not be generated by default")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="校验出镜事实、全角色章节表与主要角色场景统计")
    parser.add_argument("project_dir", type=Path)
    args = parser.parse_args()
    errors = validate_appearance_reports(args.project_dir)
    if errors:
        print("APPEARANCE VALIDATION FAILED:")
        for error in errors:
            print(f" - {error}")
        return 1
    print("APPEARANCE VALIDATION PASSED: canonical identities, chapter rows, scene de-duplication and Markdown outputs are consistent.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
